export enum AuthCodeError {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
