export enum AuthCodeError {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}

export enum PostCodeError {
  POST_NOT_FOUND = "POST_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
}
